name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/chackout
      -name: testando calculadora musical
      run: |
        pip install --user django
        python3 manage.py test